.TH "src/checker.cpp" 3 "competitive-contest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/checker.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'testlib\&.h'\fP
.br
\fR#include <bits/stdc++\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBprime\fP (int x)"
.br
.ti -1c
.RI "int \fBreadAns\fP (\fBInStream\fP &stream)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "bool \fBhas\fP [1010]"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line \fB26\fP of file \fBchecker\&.cpp\fP\&.
.SS "bool prime (int x)"

.PP
Definition at line \fB8\fP of file \fBchecker\&.cpp\fP\&.
.SS "int readAns (\fBInStream\fP & stream)"

.PP
Definition at line \fB17\fP of file \fBchecker\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "bool has[1010]"

.PP
Definition at line \fB7\fP of file \fBchecker\&.cpp\fP\&.
.SS "int n"

.PP
Definition at line \fB5\fP of file \fBchecker\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for competitive-contest from the source code\&.
