.TH "Checker" 3 "competitive-contest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Checker
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <testlib\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChecker\fP ()"
.br
.ti -1c
.RI "void \fBinitialize\fP ()"
.br
.ti -1c
.RI "std::string \fBtestset\fP () const"
.br
.ti -1c
.RI "std::string \fBgroup\fP () const"
.br
.ti -1c
.RI "void \fBsetTestset\fP (const char *const \fBtestset\fP)"
.br
.ti -1c
.RI "void \fBsetGroup\fP (const char *const \fBgroup\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4777\fP of file \fBtestlib\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Checker::Checker ()\fR [inline]\fP"

.PP
Definition at line \fB4784\fP of file \fBtestlib\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string Checker::group () const\fR [inline]\fP"

.PP
Definition at line \fB4797\fP of file \fBtestlib\&.h\fP\&.
.SS "void Checker::initialize ()\fR [inline]\fP"

.PP
Definition at line \fB4787\fP of file \fBtestlib\&.h\fP\&.
.SS "void Checker::setGroup (const char *const group)\fR [inline]\fP"

.PP
Definition at line \fB4807\fP of file \fBtestlib\&.h\fP\&.
.SS "void Checker::setTestset (const char *const testset)\fR [inline]\fP"

.PP
Definition at line \fB4803\fP of file \fBtestlib\&.h\fP\&.
.SS "std::string Checker::testset () const\fR [inline]\fP"

.PP
Definition at line \fB4791\fP of file \fBtestlib\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for competitive-contest from the source code\&.
