.TH "ConstantBound" 3 "competitive-contest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConstantBound
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <testlib\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > void \fBadjust\fP (T t)"
.br
.ti -1c
.RI "bool \fBhas_value\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBvalue\fP"
.br
.ti -1c
.RI "bool \fBbroken\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB2400\fP of file \fBtestlib\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > void ConstantBound::adjust (T t)\fR [inline]\fP"

.PP
Definition at line \fB2405\fP of file \fBtestlib\&.h\fP\&.
.SS "bool ConstantBound::has_value ()\fR [inline]\fP"

.PP
Definition at line \fB2420\fP of file \fBtestlib\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool ConstantBound::broken"

.PP
Definition at line \fB2402\fP of file \fBtestlib\&.h\fP\&.
.SS "std::string ConstantBound::value"

.PP
Definition at line \fB2401\fP of file \fBtestlib\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for competitive-contest from the source code\&.
