.TH "ConstantBounds" 3 "competitive-contest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConstantBounds
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <testlib\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBConstantBound\fP \fBlowerBound\fP"
.br
.ti -1c
.RI "\fBConstantBound\fP \fBupperBound\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB2425\fP of file \fBtestlib\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBConstantBound\fP ConstantBounds::lowerBound"

.PP
Definition at line \fB2426\fP of file \fBtestlib\&.h\fP\&.
.SS "\fBConstantBound\fP ConstantBounds::upperBound"

.PP
Definition at line \fB2427\fP of file \fBtestlib\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for competitive-contest from the source code\&.
