.TH "src/defaultsol.cpp" 3 "competitive-contest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/defaultsol.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <bits/stdc++\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBll\fP   long long"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBll\fP \fBfib\fP (\fBll\fP \fBn\fP)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ll   long long"

.PP
Definition at line \fB2\fP of file \fBdefaultsol\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBll\fP fib (\fBll\fP n)"

.PP
Definition at line \fB6\fP of file \fBdefaultsol\&.cpp\fP\&.
.SS "int main ()"

.PP
Definition at line \fB19\fP of file \fBdefaultsol\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for competitive-contest from the source code\&.
