.TH "src/fib.h" 3 "competitive-contest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/fib.h
.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBfib\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBll\fP   long long"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ll   long long"

.PP
Definition at line \fB10\fP of file \fBfib\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for competitive-contest from the source code\&.
