.TH "fib" 3 "competitive-contest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fib
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fib\&.h>\fP
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBfib\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for competitive-contest from the source code\&.
