.TH "src/fib.cpp" 3 "competitive-contest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/fib.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'fib\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBll\fP \fBfib\fP (\fBll\fP \fBn\fP)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBll\fP fib (\fBll\fP n)"

.PP
Definition at line \fB7\fP of file \fBfib\&.cpp\fP\&.
.SS "int main ()"

.PP
Definition at line \fB21\fP of file \fBfib\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for competitive-contest from the source code\&.
