.TH "generator" 3 "competitive-contest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
generator
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <generator\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgenerator\fP ()"
.br
.ti -1c
.RI "void \fBgen_input\fP (\fBll\fP max_n=1e14, \fBll\fP max_m=1e3)"
.br
.ti -1c
.RI "void \fBgen_input_all\fP ()"
.br
.ti -1c
.RI "void \fBgen_output\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB23\fP of file \fBgenerator\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "generator::generator ()\fR [inline]\fP"

.PP
Definition at line \fB35\fP of file \fBgenerator\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void generator::gen_input (\fBll\fP max_n = \fR1e14\fP, \fBll\fP max_m = \fR1e3\fP)\fR [inline]\fP"

.PP
Definition at line \fB37\fP of file \fBgenerator\&.h\fP\&.
.SS "void generator::gen_input_all ()\fR [inline]\fP"

.PP
Definition at line \fB63\fP of file \fBgenerator\&.h\fP\&.
.SS "void generator::gen_output ()\fR [inline]\fP"

.PP
Definition at line \fB82\fP of file \fBgenerator\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for competitive-contest from the source code\&.
