.TH "src/generator.cpp" 3 "competitive-contest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/generator.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'generator\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line \fB7\fP of file \fBgenerator\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for competitive-contest from the source code\&.
