.TH "src/generator.h" 3 "competitive-contest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/generator.h
.SH SYNOPSIS
.br
.PP
\fR#include <fstream>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <random>\fP
.br
\fR#include <string>\fP
.br
\fR#include <sys/stat\&.h>\fP
.br
\fR#include <vector>\fP
.br
\fR#include '\&./officialsol\&.cpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgenerator\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBll\fP   long long"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct stat \fBinfo\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ll   long long"

.PP
Definition at line \fB17\fP of file \fBgenerator\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "struct stat info"

.PP
Definition at line \fB21\fP of file \fBgenerator\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for competitive-contest from the source code\&.
