.TH "InputStreamReader" 3 "competitive-contest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InputStreamReader
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <testlib\&.h>\fP
.PP
Inherited by \fBBufferedFileInputStreamReader\fP, \fBFileInputStreamReader\fP, and \fBStringInputStreamReader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBsetTestCase\fP (int testCase)=0"
.br
.ti -1c
.RI "virtual std::vector< int > \fBgetReadChars\fP ()=0"
.br
.ti -1c
.RI "virtual int \fBcurChar\fP ()=0"
.br
.ti -1c
.RI "virtual int \fBnextChar\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBskipChar\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBunreadChar\fP (int c)=0"
.br
.ti -1c
.RI "virtual std::string \fBgetName\fP ()=0"
.br
.ti -1c
.RI "virtual bool \fBeof\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBclose\fP ()=0"
.br
.ti -1c
.RI "virtual int \fBgetLine\fP ()=0"
.br
.ti -1c
.RI "virtual \fB~InputStreamReader\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1663\fP of file \fBtestlib\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "InputStreamReader::~InputStreamReader ()\fR [pure virtual]\fP"

.PP
Definition at line \fB1688\fP of file \fBtestlib\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void InputStreamReader::close ()\fR [pure virtual]\fP"

.PP
Implemented in \fBStringInputStreamReader\fP, \fBFileInputStreamReader\fP, and \fBBufferedFileInputStreamReader\fP\&.
.SS "virtual int InputStreamReader::curChar ()\fR [pure virtual]\fP"

.PP
Implemented in \fBStringInputStreamReader\fP, \fBFileInputStreamReader\fP, and \fBBufferedFileInputStreamReader\fP\&.
.SS "virtual bool InputStreamReader::eof ()\fR [pure virtual]\fP"

.PP
Implemented in \fBStringInputStreamReader\fP, \fBFileInputStreamReader\fP, and \fBBufferedFileInputStreamReader\fP\&.
.SS "virtual int InputStreamReader::getLine ()\fR [pure virtual]\fP"

.PP
Implemented in \fBStringInputStreamReader\fP, \fBFileInputStreamReader\fP, and \fBBufferedFileInputStreamReader\fP\&.
.SS "virtual std::string InputStreamReader::getName ()\fR [pure virtual]\fP"

.PP
Implemented in \fBStringInputStreamReader\fP, \fBFileInputStreamReader\fP, and \fBBufferedFileInputStreamReader\fP\&.
.SS "virtual std::vector< int > InputStreamReader::getReadChars ()\fR [pure virtual]\fP"

.PP
Implemented in \fBStringInputStreamReader\fP, \fBFileInputStreamReader\fP, and \fBBufferedFileInputStreamReader\fP\&.
.SS "virtual int InputStreamReader::nextChar ()\fR [pure virtual]\fP"

.PP
Implemented in \fBStringInputStreamReader\fP, \fBFileInputStreamReader\fP, and \fBBufferedFileInputStreamReader\fP\&.
.SS "virtual void InputStreamReader::setTestCase (int testCase)\fR [pure virtual]\fP"

.PP
Implemented in \fBFileInputStreamReader\fP, \fBStringInputStreamReader\fP, and \fBBufferedFileInputStreamReader\fP\&.
.SS "virtual void InputStreamReader::skipChar ()\fR [pure virtual]\fP"

.PP
Implemented in \fBStringInputStreamReader\fP, \fBFileInputStreamReader\fP, and \fBBufferedFileInputStreamReader\fP\&.
.SS "virtual void InputStreamReader::unreadChar (int c)\fR [pure virtual]\fP"

.PP
Implemented in \fBStringInputStreamReader\fP, \fBFileInputStreamReader\fP, and \fBBufferedFileInputStreamReader\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for competitive-contest from the source code\&.
