.TH "InStream" 3 "competitive-contest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InStream
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <testlib\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInStream\fP ()"
.br
.ti -1c
.RI "\fB~InStream\fP ()"
.br
.ti -1c
.RI "\fBInStream\fP (const \fBInStream\fP &baseStream, std::string content)"
.br
.ti -1c
.RI "void \fBinit\fP (std::string fileName, \fBTMode\fP \fBmode\fP)"
.br
.ti -1c
.RI "void \fBinit\fP (std::FILE *f, \fBTMode\fP \fBmode\fP)"
.br
.ti -1c
.RI "void \fBsetTestCase\fP (int testCase)"
.br
.ti -1c
.RI "std::vector< int > \fBgetReadChars\fP ()"
.br
.ti -1c
.RI "void \fBskipBlanks\fP ()"
.br
.ti -1c
.RI "char \fBcurChar\fP ()"
.br
.ti -1c
.RI "void \fBskipChar\fP ()"
.br
.ti -1c
.RI "char \fBnextChar\fP ()"
.br
.ti -1c
.RI "char \fBreadChar\fP ()"
.br
.ti -1c
.RI "char \fBreadChar\fP (char c)"
.br
.ti -1c
.RI "char \fBreadSpace\fP ()"
.br
.ti -1c
.RI "void \fBunreadChar\fP (char c)"
.br
.ti -1c
.RI "void \fBreset\fP (std::FILE *file=NULL)"
.br
.ti -1c
.RI "bool \fBeof\fP ()"
.br
.ti -1c
.RI "bool \fBseekEof\fP ()"
.br
.ti -1c
.RI "bool \fBeoln\fP ()"
.br
.ti -1c
.RI "bool \fBseekEoln\fP ()"
.br
.ti -1c
.RI "void \fBnextLine\fP ()"
.br
.ti -1c
.RI "std::string \fBreadWord\fP ()"
.br
.ti -1c
.RI "std::string \fBreadToken\fP ()"
.br
.ti -1c
.RI "std::string \fBreadWord\fP (const std::string &ptrn, const std::string &variableName='')"
.br
.ti -1c
.RI "std::string \fBreadWord\fP (const \fBpattern\fP &p, const std::string &variableName='')"
.br
.ti -1c
.RI "std::vector< std::string > \fBreadWords\fP (int size, const std::string &ptrn, const std::string &variablesName='', int indexBase=1)"
.br
.ti -1c
.RI "std::vector< std::string > \fBreadWords\fP (int size, const \fBpattern\fP &p, const std::string &variablesName='', int indexBase=1)"
.br
.ti -1c
.RI "std::vector< std::string > \fBreadWords\fP (int size, int indexBase=1)"
.br
.ti -1c
.RI "std::string \fBreadToken\fP (const std::string &ptrn, const std::string &variableName='')"
.br
.ti -1c
.RI "std::string \fBreadToken\fP (const \fBpattern\fP &p, const std::string &variableName='')"
.br
.ti -1c
.RI "std::vector< std::string > \fBreadTokens\fP (int size, const std::string &ptrn, const std::string &variablesName='', int indexBase=1)"
.br
.ti -1c
.RI "std::vector< std::string > \fBreadTokens\fP (int size, const \fBpattern\fP &p, const std::string &variablesName='', int indexBase=1)"
.br
.ti -1c
.RI "std::vector< std::string > \fBreadTokens\fP (int size, int indexBase=1)"
.br
.ti -1c
.RI "void \fBreadWordTo\fP (std::string &result)"
.br
.ti -1c
.RI "void \fBreadWordTo\fP (std::string &result, const \fBpattern\fP &p, const std::string &variableName='')"
.br
.ti -1c
.RI "void \fBreadWordTo\fP (std::string &result, const std::string &ptrn, const std::string &variableName='')"
.br
.ti -1c
.RI "void \fBreadTokenTo\fP (std::string &result)"
.br
.ti -1c
.RI "void \fBreadTokenTo\fP (std::string &result, const \fBpattern\fP &p, const std::string &variableName='')"
.br
.ti -1c
.RI "void \fBreadTokenTo\fP (std::string &result, const std::string &ptrn, const std::string &variableName='')"
.br
.ti -1c
.RI "long long \fBreadLong\fP ()"
.br
.ti -1c
.RI "unsigned long long \fBreadUnsignedLong\fP ()"
.br
.ti -1c
.RI "int \fBreadInteger\fP ()"
.br
.ti -1c
.RI "int \fBreadInt\fP ()"
.br
.ti -1c
.RI "long long \fBreadLong\fP (long long minv, long long maxv, const std::string &variableName='')"
.br
.ti -1c
.RI "std::vector< long long > \fBreadLongs\fP (int size, long long minv, long long maxv, const std::string &variablesName='', int indexBase=1)"
.br
.ti -1c
.RI "std::vector< long long > \fBreadLongs\fP (int size, int indexBase=1)"
.br
.ti -1c
.RI "unsigned long long \fBreadUnsignedLong\fP (unsigned long long minv, unsigned long long maxv, const std::string &variableName='')"
.br
.ti -1c
.RI "std::vector< unsigned long long > \fBreadUnsignedLongs\fP (int size, unsigned long long minv, unsigned long long maxv, const std::string &variablesName='', int indexBase=1)"
.br
.ti -1c
.RI "std::vector< unsigned long long > \fBreadUnsignedLongs\fP (int size, int indexBase=1)"
.br
.ti -1c
.RI "unsigned long long \fBreadLong\fP (unsigned long long minv, unsigned long long maxv, const std::string &variableName='')"
.br
.ti -1c
.RI "std::vector< unsigned long long > \fBreadLongs\fP (int size, unsigned long long minv, unsigned long long maxv, const std::string &variablesName='', int indexBase=1)"
.br
.ti -1c
.RI "int \fBreadInteger\fP (int minv, int maxv, const std::string &variableName='')"
.br
.ti -1c
.RI "int \fBreadInt\fP (int minv, int maxv, const std::string &variableName='')"
.br
.ti -1c
.RI "std::vector< int > \fBreadIntegers\fP (int size, int minv, int maxv, const std::string &variablesName='', int indexBase=1)"
.br
.ti -1c
.RI "std::vector< int > \fBreadIntegers\fP (int size, int indexBase=1)"
.br
.ti -1c
.RI "std::vector< int > \fBreadInts\fP (int size, int minv, int maxv, const std::string &variablesName='', int indexBase=1)"
.br
.ti -1c
.RI "std::vector< int > \fBreadInts\fP (int size, int indexBase=1)"
.br
.ti -1c
.RI "double \fBreadReal\fP ()"
.br
.ti -1c
.RI "double \fBreadDouble\fP ()"
.br
.ti -1c
.RI "double \fBreadReal\fP (double minv, double maxv, const std::string &variableName='')"
.br
.ti -1c
.RI "std::vector< double > \fBreadReals\fP (int size, double minv, double maxv, const std::string &variablesName='', int indexBase=1)"
.br
.ti -1c
.RI "std::vector< double > \fBreadReals\fP (int size, int indexBase=1)"
.br
.ti -1c
.RI "double \fBreadDouble\fP (double minv, double maxv, const std::string &variableName='')"
.br
.ti -1c
.RI "std::vector< double > \fBreadDoubles\fP (int size, double minv, double maxv, const std::string &variablesName='', int indexBase=1)"
.br
.ti -1c
.RI "std::vector< double > \fBreadDoubles\fP (int size, int indexBase=1)"
.br
.ti -1c
.RI "double \fBreadStrictReal\fP (double minv, double maxv, int minAfterPointDigitCount, int maxAfterPointDigitCount, const std::string &variableName='')"
.br
.ti -1c
.RI "std::vector< double > \fBreadStrictReals\fP (int size, double minv, double maxv, int minAfterPointDigitCount, int maxAfterPointDigitCount, const std::string &variablesName='', int indexBase=1)"
.br
.ti -1c
.RI "double \fBreadStrictDouble\fP (double minv, double maxv, int minAfterPointDigitCount, int maxAfterPointDigitCount, const std::string &variableName='')"
.br
.ti -1c
.RI "std::vector< double > \fBreadStrictDoubles\fP (int size, double minv, double maxv, int minAfterPointDigitCount, int maxAfterPointDigitCount, const std::string &variablesName='', int indexBase=1)"
.br
.ti -1c
.RI "std::string \fBreadString\fP ()"
.br
.ti -1c
.RI "std::vector< std::string > \fBreadStrings\fP (int size, int indexBase=1)"
.br
.ti -1c
.RI "void \fBreadStringTo\fP (std::string &result)"
.br
.ti -1c
.RI "std::string \fBreadString\fP (const \fBpattern\fP &p, const std::string &variableName='')"
.br
.ti -1c
.RI "std::string \fBreadString\fP (const std::string &ptrn, const std::string &variableName='')"
.br
.ti -1c
.RI "std::vector< std::string > \fBreadStrings\fP (int size, const \fBpattern\fP &p, const std::string &variableName='', int indexBase=1)"
.br
.ti -1c
.RI "std::vector< std::string > \fBreadStrings\fP (int size, const std::string &ptrn, const std::string &variableName='', int indexBase=1)"
.br
.ti -1c
.RI "void \fBreadStringTo\fP (std::string &result, const \fBpattern\fP &p, const std::string &variableName='')"
.br
.ti -1c
.RI "void \fBreadStringTo\fP (std::string &result, const std::string &ptrn, const std::string &variableName='')"
.br
.ti -1c
.RI "std::string \fBreadLine\fP ()"
.br
.ti -1c
.RI "std::vector< std::string > \fBreadLines\fP (int size, int indexBase=1)"
.br
.ti -1c
.RI "void \fBreadLineTo\fP (std::string &result)"
.br
.ti -1c
.RI "std::string \fBreadLine\fP (const \fBpattern\fP &p, const std::string &variableName='')"
.br
.ti -1c
.RI "std::string \fBreadLine\fP (const std::string &ptrn, const std::string &variableName='')"
.br
.ti -1c
.RI "std::vector< std::string > \fBreadLines\fP (int size, const \fBpattern\fP &p, const std::string &variableName='', int indexBase=1)"
.br
.ti -1c
.RI "std::vector< std::string > \fBreadLines\fP (int size, const std::string &ptrn, const std::string &variableName='', int indexBase=1)"
.br
.ti -1c
.RI "void \fBreadLineTo\fP (std::string &result, const \fBpattern\fP &p, const std::string &variableName='')"
.br
.ti -1c
.RI "void \fBreadLineTo\fP (std::string &result, const std::string &ptrn, const std::string &variableName='')"
.br
.ti -1c
.RI "void \fBreadEoln\fP ()"
.br
.ti -1c
.RI "void \fBreadEof\fP ()"
.br
.ti -1c
.RI "\fBNORETURN\fP void \fBquit\fP (\fBTResult\fP result, const char *msg)"
.br
.ti -1c
.RI "\fBNORETURN\fP void \fBquitf\fP (\fBTResult\fP result, const char *msg,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBquitif\fP (bool condition, \fBTResult\fP result, const char *msg,\&.\&.\&.)"
.br
.ti -1c
.RI "\fBNORETURN\fP void \fBquits\fP (\fBTResult\fP result, std::string msg)"
.br
.ti -1c
.RI "void \fBensuref\fP (bool cond, const char *\fBformat\fP,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fB__testlib_ensure\fP (bool cond, std::string message)"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.ti -1c
.RI "void \fBxmlSafeWrite\fP (std::FILE *file, const char *msg)"
.br
.ti -1c
.RI "void \fBskipBom\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBtextColor\fP (\fBWORD\fP color)"
.br
.ti -1c
.RI "static void \fBquitscr\fP (\fBWORD\fP color, const char *msg)"
.br
.ti -1c
.RI "static void \fBquitscrS\fP (\fBWORD\fP color, std::string msg)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBInputStreamReader\fP * \fBreader\fP"
.br
.ti -1c
.RI "int \fBlastLine\fP"
.br
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "\fBTMode\fP \fBmode\fP"
.br
.ti -1c
.RI "bool \fBopened\fP"
.br
.ti -1c
.RI "bool \fBstdfile\fP"
.br
.ti -1c
.RI "bool \fBstrict\fP"
.br
.ti -1c
.RI "int \fBwordReserveSize\fP"
.br
.ti -1c
.RI "std::string \fB_tmpReadToken\fP"
.br
.ti -1c
.RI "int \fBreadManyIteration\fP"
.br
.ti -1c
.RI "size_t \fBmaxFileSize\fP"
.br
.ti -1c
.RI "size_t \fBmaxTokenLength\fP"
.br
.ti -1c
.RI "size_t \fBmaxMessageLength\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBNO_INDEX\fP = INT_MAX"
.br
.ti -1c
.RI "static const char \fBOPEN_BRACKET\fP = char(11)"
.br
.ti -1c
.RI "static const char \fBCLOSE_BRACKET\fP = char(17)"
.br
.ti -1c
.RI "static const \fBWORD\fP \fBLightGray\fP = 0x07"
.br
.ti -1c
.RI "static const \fBWORD\fP \fBLightRed\fP = 0x0c"
.br
.ti -1c
.RI "static const \fBWORD\fP \fBLightCyan\fP = 0x0b"
.br
.ti -1c
.RI "static const \fBWORD\fP \fBLightGreen\fP = 0x0a"
.br
.ti -1c
.RI "static const \fBWORD\fP \fBLightYellow\fP = 0x0e"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1998\fP of file \fBtestlib\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "InStream::InStream ()"

.PP
Definition at line \fB2828\fP of file \fBtestlib\&.h\fP\&.
.SS "InStream::~InStream ()"

.PP
Definition at line \fB2857\fP of file \fBtestlib\&.h\fP\&.
.SS "InStream::InStream (const \fBInStream\fP & baseStream, std::string content)"

.PP
Definition at line \fB2843\fP of file \fBtestlib\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void InStream::__testlib_ensure (bool cond, std::string message)"

.PP
Definition at line \fB4396\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::close ()"

.PP
Definition at line \fB4401\fP of file \fBtestlib\&.h\fP\&.
.SS "char InStream::curChar ()"

.PP
Definition at line \fB3331\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::ensuref (bool cond, const char * format,  \&.\&.\&.)"

.PP
Definition at line \fB4389\fP of file \fBtestlib\&.h\fP\&.
.SS "bool InStream::eof ()"

.PP
Definition at line \fB4154\fP of file \fBtestlib\&.h\fP\&.
.SS "bool InStream::eoln ()"

.PP
Definition at line \fB4168\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< int > InStream::getReadChars ()"

.PP
Definition at line \fB2872\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::init (std::FILE * f, \fBTMode\fP mode)"

.PP
Definition at line \fB3301\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::init (std::string fileName, \fBTMode\fP mode)"

.PP
Definition at line \fB3277\fP of file \fBtestlib\&.h\fP\&.
.SS "char InStream::nextChar ()"

.PP
Definition at line \fB3335\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::nextLine ()"

.PP
Definition at line \fB4246\fP of file \fBtestlib\&.h\fP\&.
.SS "\fBNORETURN\fP void InStream::quit (\fBTResult\fP result, const char * msg)"

.PP
Definition at line \fB3046\fP of file \fBtestlib\&.h\fP\&.
.SS "\fBNORETURN\fP void InStream::quitf (\fBTResult\fP result, const char * msg,  \&.\&.\&.)"

.PP
Definition at line \fB3189\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::quitif (bool condition, \fBTResult\fP result, const char * msg,  \&.\&.\&.)"

.PP
Definition at line \fB3197\fP of file \fBtestlib\&.h\fP\&.
.SS "\fBNORETURN\fP void InStream::quits (\fBTResult\fP result, std::string msg)"

.PP
Definition at line \fB3204\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::quitscr (\fBWORD\fP color, const char * msg)\fR [static]\fP"

.PP
Definition at line \fB3239\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::quitscrS (\fBWORD\fP color, std::string msg)\fR [static]\fP"

.PP
Definition at line \fB3235\fP of file \fBtestlib\&.h\fP\&.
.SS "char InStream::readChar ()"

.PP
Definition at line \fB3339\fP of file \fBtestlib\&.h\fP\&.
.SS "char InStream::readChar (char c)"

.PP
Definition at line \fB3343\fP of file \fBtestlib\&.h\fP\&.
.SS "double InStream::readDouble ()"

.PP
Definition at line \fB4022\fP of file \fBtestlib\&.h\fP\&.
.SS "double InStream::readDouble (double minv, double maxv, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB4071\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< double > InStream::readDoubles (int size, double minv, double maxv, const std::string & variablesName = \fR''\fP, int indexBase = \fR1\fP)"

.PP
Definition at line \fB4076\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< double > InStream::readDoubles (int size, int indexBase = \fR1\fP)"

.PP
Definition at line \fB4082\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::readEof ()"

.PP
Definition at line \fB4224\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::readEoln ()"

.PP
Definition at line \fB4218\fP of file \fBtestlib\&.h\fP\&.
.SS "int InStream::readInt ()"

.PP
Definition at line \fB3956\fP of file \fBtestlib\&.h\fP\&.
.SS "int InStream::readInt (int minv, int maxv, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB3960\fP of file \fBtestlib\&.h\fP\&.
.SS "int InStream::readInteger ()"

.PP
Definition at line \fB3832\fP of file \fBtestlib\&.h\fP\&.
.SS "int InStream::readInteger (int minv, int maxv, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB3991\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< int > InStream::readIntegers (int size, int indexBase = \fR1\fP)"

.PP
Definition at line \fB4011\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< int > InStream::readIntegers (int size, int minv, int maxv, const std::string & variablesName = \fR''\fP, int indexBase = \fR1\fP)"

.PP
Definition at line \fB4005\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< int > InStream::readInts (int size, int indexBase = \fR1\fP)"

.PP
Definition at line \fB4001\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< int > InStream::readInts (int size, int minv, int maxv, const std::string & variablesName = \fR''\fP, int indexBase = \fR1\fP)"

.PP
Definition at line \fB3995\fP of file \fBtestlib\&.h\fP\&.
.SS "std::string InStream::readLine ()"

.PP
Definition at line \fB4347\fP of file \fBtestlib\&.h\fP\&.
.SS "std::string InStream::readLine (const \fBpattern\fP & p, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB4363\fP of file \fBtestlib\&.h\fP\&.
.SS "std::string InStream::readLine (const std::string & ptrn, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB4374\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< std::string > InStream::readLines (int size, const \fBpattern\fP & p, const std::string & variableName = \fR''\fP, int indexBase = \fR1\fP)"

.PP
Definition at line \fB4368\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< std::string > InStream::readLines (int size, const std::string & ptrn, const std::string & variableName = \fR''\fP, int indexBase = \fR1\fP)"

.PP
Definition at line \fB4379\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< std::string > InStream::readLines (int size, int indexBase = \fR1\fP)"

.PP
Definition at line \fB4351\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::readLineTo (std::string & result)"

.PP
Definition at line \fB4343\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::readLineTo (std::string & result, const \fBpattern\fP & p, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB4355\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::readLineTo (std::string & result, const std::string & ptrn, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB4359\fP of file \fBtestlib\&.h\fP\&.
.SS "long long InStream::readLong ()"

.PP
Definition at line \fB3845\fP of file \fBtestlib\&.h\fP\&.
.SS "long long InStream::readLong (long long minv, long long maxv, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB3863\fP of file \fBtestlib\&.h\fP\&.
.SS "unsigned long long InStream::readLong (unsigned long long minv, unsigned long long maxv, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB3952\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< long long > InStream::readLongs (int size, int indexBase = \fR1\fP)"

.PP
Definition at line \fB3901\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< long long > InStream::readLongs (int size, long long minv, long long maxv, const std::string & variablesName = \fR''\fP, int indexBase = \fR1\fP)"

.PP
Definition at line \fB3895\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< unsigned long long > InStream::readLongs (int size, unsigned long long minv, unsigned long long maxv, const std::string & variablesName = \fR''\fP, int indexBase = \fR1\fP)"

.SS "double InStream::readReal ()"

.PP
Definition at line \fB4015\fP of file \fBtestlib\&.h\fP\&.
.SS "double InStream::readReal (double minv, double maxv, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB4026\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< double > InStream::readReals (int size, double minv, double maxv, const std::string & variablesName = \fR''\fP, int indexBase = \fR1\fP)"

.PP
Definition at line \fB4061\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< double > InStream::readReals (int size, int indexBase = \fR1\fP)"

.PP
Definition at line \fB4067\fP of file \fBtestlib\&.h\fP\&.
.SS "char InStream::readSpace ()"

.PP
Definition at line \fB3357\fP of file \fBtestlib\&.h\fP\&.
.SS "double InStream::readStrictDouble (double minv, double maxv, int minAfterPointDigitCount, int maxAfterPointDigitCount, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB4136\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< double > InStream::readStrictDoubles (int size, double minv, double maxv, int minAfterPointDigitCount, int maxAfterPointDigitCount, const std::string & variablesName = \fR''\fP, int indexBase = \fR1\fP)"

.PP
Definition at line \fB4144\fP of file \fBtestlib\&.h\fP\&.
.SS "double InStream::readStrictReal (double minv, double maxv, int minAfterPointDigitCount, int maxAfterPointDigitCount, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB4086\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< double > InStream::readStrictReals (int size, double minv, double maxv, int minAfterPointDigitCount, int maxAfterPointDigitCount, const std::string & variablesName = \fR''\fP, int indexBase = \fR1\fP)"

.PP
Definition at line \fB4126\fP of file \fBtestlib\&.h\fP\&.
.SS "std::string InStream::readString ()"

.PP
Definition at line \fB4280\fP of file \fBtestlib\&.h\fP\&.
.SS "std::string InStream::readString (const \fBpattern\fP & p, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB4318\fP of file \fBtestlib\&.h\fP\&.
.SS "std::string InStream::readString (const std::string & ptrn, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB4330\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< std::string > InStream::readStrings (int size, const \fBpattern\fP & p, const std::string & variableName = \fR''\fP, int indexBase = \fR1\fP)"

.PP
Definition at line \fB4324\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< std::string > InStream::readStrings (int size, const std::string & ptrn, const std::string & variableName = \fR''\fP, int indexBase = \fR1\fP)"

.PP
Definition at line \fB4336\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< std::string > InStream::readStrings (int size, int indexBase = \fR1\fP)"

.PP
Definition at line \fB4285\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::readStringTo (std::string & result)"

.PP
Definition at line \fB4250\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::readStringTo (std::string & result, const \fBpattern\fP & p, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB4289\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::readStringTo (std::string & result, const std::string & ptrn, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB4314\fP of file \fBtestlib\&.h\fP\&.
.SS "std::string InStream::readToken ()"

.PP
Definition at line \fB3412\fP of file \fBtestlib\&.h\fP\&.
.SS "std::string InStream::readToken (const \fBpattern\fP & p, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB3507\fP of file \fBtestlib\&.h\fP\&.
.SS "std::string InStream::readToken (const std::string & ptrn, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB3522\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< std::string > InStream::readTokens (int size, const \fBpattern\fP & p, const std::string & variablesName = \fR''\fP, int indexBase = \fR1\fP)"

.PP
Definition at line \fB3512\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< std::string > InStream::readTokens (int size, const std::string & ptrn, const std::string & variablesName = \fR''\fP, int indexBase = \fR1\fP)"

.PP
Definition at line \fB3527\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< std::string > InStream::readTokens (int size, int indexBase = \fR1\fP)"

.PP
Definition at line \fB3518\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::readTokenTo (std::string & result)"

.PP
Definition at line \fB3416\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::readTokenTo (std::string & result, const \fBpattern\fP & p, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB3552\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::readTokenTo (std::string & result, const std::string & ptrn, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB3556\fP of file \fBtestlib\&.h\fP\&.
.SS "unsigned long long InStream::readUnsignedLong ()"

.PP
Definition at line \fB3854\fP of file \fBtestlib\&.h\fP\&.
.SS "unsigned long long InStream::readUnsignedLong (unsigned long long minv, unsigned long long maxv, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB3906\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< unsigned long long > InStream::readUnsignedLongs (int size, int indexBase = \fR1\fP)"

.PP
Definition at line \fB3947\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< unsigned long long > InStream::readUnsignedLongs (int size, unsigned long long minv, unsigned long long maxv, const std::string & variablesName = \fR''\fP, int indexBase = \fR1\fP)"

.PP
Definition at line \fB3940\fP of file \fBtestlib\&.h\fP\&.
.SS "std::string InStream::readWord ()"

.PP
Definition at line \fB3374\fP of file \fBtestlib\&.h\fP\&.
.SS "std::string InStream::readWord (const \fBpattern\fP & p, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB3457\fP of file \fBtestlib\&.h\fP\&.
.SS "std::string InStream::readWord (const std::string & ptrn, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB3495\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< std::string > InStream::readWords (int size, const \fBpattern\fP & p, const std::string & variablesName = \fR''\fP, int indexBase = \fR1\fP)"

.PP
Definition at line \fB3485\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< std::string > InStream::readWords (int size, const std::string & ptrn, const std::string & variablesName = \fR''\fP, int indexBase = \fR1\fP)"

.PP
Definition at line \fB3500\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< std::string > InStream::readWords (int size, int indexBase = \fR1\fP)"

.PP
Definition at line \fB3491\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::readWordTo (std::string & result)"

.PP
Definition at line \fB3379\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::readWordTo (std::string & result, const \fBpattern\fP & p, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB3534\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::readWordTo (std::string & result, const std::string & ptrn, const std::string & variableName = \fR''\fP)"

.PP
Definition at line \fB3548\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::reset (std::FILE * file = \fRNULL\fP)"

.PP
Definition at line \fB3247\fP of file \fBtestlib\&.h\fP\&.
.SS "bool InStream::seekEof ()"

.PP
Definition at line \fB4161\fP of file \fBtestlib\&.h\fP\&.
.SS "bool InStream::seekEoln ()"

.PP
Definition at line \fB4233\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::setTestCase (int testCase)"

.PP
Definition at line \fB2865\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::skipBlanks ()"

.PP
Definition at line \fB3369\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::skipBom ()"

.PP
Definition at line \fB3316\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::skipChar ()"

.PP
Definition at line \fB3365\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::textColor (\fBWORD\fP color)\fR [static]\fP"

.PP
Definition at line \fB2924\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::unreadChar (char c)"

.PP
Definition at line \fB3361\fP of file \fBtestlib\&.h\fP\&.
.SS "void InStream::xmlSafeWrite (std::FILE * file, const char * msg)"

.PP
Definition at line \fB3208\fP of file \fBtestlib\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string InStream::_tmpReadToken"

.PP
Definition at line \fB2017\fP of file \fBtestlib\&.h\fP\&.
.SS "const char InStream::CLOSE_BRACKET = char(17)\fR [static]\fP"

.PP
Definition at line \fB2346\fP of file \fBtestlib\&.h\fP\&.
.SS "int InStream::lastLine"

.PP
Definition at line \fB2008\fP of file \fBtestlib\&.h\fP\&.
.SS "const \fBWORD\fP InStream::LightCyan = 0x0b\fR [static]\fP"

.PP
Definition at line \fB2350\fP of file \fBtestlib\&.h\fP\&.
.SS "const \fBWORD\fP InStream::LightGray = 0x07\fR [static]\fP"

.PP
Definition at line \fB2348\fP of file \fBtestlib\&.h\fP\&.
.SS "const \fBWORD\fP InStream::LightGreen = 0x0a\fR [static]\fP"

.PP
Definition at line \fB2351\fP of file \fBtestlib\&.h\fP\&.
.SS "const \fBWORD\fP InStream::LightRed = 0x0c\fR [static]\fP"

.PP
Definition at line \fB2349\fP of file \fBtestlib\&.h\fP\&.
.SS "const \fBWORD\fP InStream::LightYellow = 0x0e\fR [static]\fP"

.PP
Definition at line \fB2352\fP of file \fBtestlib\&.h\fP\&.
.SS "size_t InStream::maxFileSize"

.PP
Definition at line \fB2020\fP of file \fBtestlib\&.h\fP\&.
.SS "size_t InStream::maxMessageLength"

.PP
Definition at line \fB2022\fP of file \fBtestlib\&.h\fP\&.
.SS "size_t InStream::maxTokenLength"

.PP
Definition at line \fB2021\fP of file \fBtestlib\&.h\fP\&.
.SS "\fBTMode\fP InStream::mode"

.PP
Definition at line \fB2011\fP of file \fBtestlib\&.h\fP\&.
.SS "std::string InStream::name"

.PP
Definition at line \fB2010\fP of file \fBtestlib\&.h\fP\&.
.SS "const int InStream::NO_INDEX = INT_MAX\fR [static]\fP"

.PP
Definition at line \fB2344\fP of file \fBtestlib\&.h\fP\&.
.SS "const char InStream::OPEN_BRACKET = char(11)\fR [static]\fP"

.PP
Definition at line \fB2345\fP of file \fBtestlib\&.h\fP\&.
.SS "bool InStream::opened"

.PP
Definition at line \fB2012\fP of file \fBtestlib\&.h\fP\&.
.SS "\fBInputStreamReader\fP* InStream::reader"

.PP
Definition at line \fB2007\fP of file \fBtestlib\&.h\fP\&.
.SS "int InStream::readManyIteration"

.PP
Definition at line \fB2019\fP of file \fBtestlib\&.h\fP\&.
.SS "bool InStream::stdfile"

.PP
Definition at line \fB2013\fP of file \fBtestlib\&.h\fP\&.
.SS "bool InStream::strict"

.PP
Definition at line \fB2014\fP of file \fBtestlib\&.h\fP\&.
.SS "int InStream::wordReserveSize"

.PP
Definition at line \fB2016\fP of file \fBtestlib\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for competitive-contest from the source code\&.
