.TH "src/officialsol.cpp" 3 "competitive-contest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/officialsol.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBll\fP   long long"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBll\fP \fBfib_fast\fP (\fBll\fP \fBn\fP, \fBll\fP m)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ll   long long"

.PP
Definition at line \fB3\fP of file \fBofficialsol\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBll\fP fib_fast (\fBll\fP n, \fBll\fP m)"

.PP
Definition at line \fB5\fP of file \fBofficialsol\&.cpp\fP\&.
.SS "int main ()"

.PP
Definition at line \fB37\fP of file \fBofficialsol\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for competitive-contest from the source code\&.
