.TH "pattern" 3 "competitive-contest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pattern
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <testlib\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpattern\fP (std::string s)"
.br
.ti -1c
.RI "std::string \fBnext\fP (\fBrandom_t\fP &\fBrnd\fP) const"
.br
.ti -1c
.RI "bool \fBmatches\fP (const std::string &s) const"
.br
.ti -1c
.RI "std::string \fBsrc\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB713\fP of file \fBtestlib\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pattern::pattern (std::string s)"

.PP
Definition at line \fB1524\fP of file \fBtestlib\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool pattern::matches (const std::string & s) const"

.PP
Definition at line \fB1294\fP of file \fBtestlib\&.h\fP\&.
.SS "std::string pattern::next (\fBrandom_t\fP & rnd) const"

.PP
Definition at line \fB1369\fP of file \fBtestlib\&.h\fP\&.
.SS "std::string pattern::src () const"

.PP
Definition at line \fB1344\fP of file \fBtestlib\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for competitive-contest from the source code\&.
