.TH "StringInputStreamReader" 3 "competitive-contest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StringInputStreamReader
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <testlib\&.h>\fP
.PP
Inherits \fBInputStreamReader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStringInputStreamReader\fP (const std::string &content)"
.br
.ti -1c
.RI "void \fBsetTestCase\fP (int)"
.br
.ti -1c
.RI "std::vector< int > \fBgetReadChars\fP ()"
.br
.ti -1c
.RI "int \fBcurChar\fP ()"
.br
.ti -1c
.RI "int \fBnextChar\fP ()"
.br
.ti -1c
.RI "void \fBskipChar\fP ()"
.br
.ti -1c
.RI "void \fBunreadChar\fP (int c)"
.br
.ti -1c
.RI "std::string \fBgetName\fP ()"
.br
.ti -1c
.RI "int \fBgetLine\fP ()"
.br
.ti -1c
.RI "bool \fBeof\fP ()"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBInputStreamReader\fP
.in +1c
.ti -1c
.RI "virtual \fB~InputStreamReader\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1692\fP of file \fBtestlib\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StringInputStreamReader::StringInputStreamReader (const std::string & content)\fR [inline]\fP"

.PP
Definition at line \fB1698\fP of file \fBtestlib\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void StringInputStreamReader::close ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBInputStreamReader\fP\&.
.PP
Definition at line \fB1749\fP of file \fBtestlib\&.h\fP\&.
.SS "int StringInputStreamReader::curChar ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBInputStreamReader\fP\&.
.PP
Definition at line \fB1710\fP of file \fBtestlib\&.h\fP\&.
.SS "bool StringInputStreamReader::eof ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBInputStreamReader\fP\&.
.PP
Definition at line \fB1745\fP of file \fBtestlib\&.h\fP\&.
.SS "int StringInputStreamReader::getLine ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBInputStreamReader\fP\&.
.PP
Definition at line \fB1741\fP of file \fBtestlib\&.h\fP\&.
.SS "std::string StringInputStreamReader::getName ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBInputStreamReader\fP\&.
.PP
Definition at line \fB1737\fP of file \fBtestlib\&.h\fP\&.
.SS "std::vector< int > StringInputStreamReader::getReadChars ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBInputStreamReader\fP\&.
.PP
Definition at line \fB1706\fP of file \fBtestlib\&.h\fP\&.
.SS "int StringInputStreamReader::nextChar ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBInputStreamReader\fP\&.
.PP
Definition at line \fB1717\fP of file \fBtestlib\&.h\fP\&.
.SS "void StringInputStreamReader::setTestCase (int)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBInputStreamReader\fP\&.
.PP
Definition at line \fB1702\fP of file \fBtestlib\&.h\fP\&.
.SS "void StringInputStreamReader::skipChar ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBInputStreamReader\fP\&.
.PP
Definition at line \fB1725\fP of file \fBtestlib\&.h\fP\&.
.SS "void StringInputStreamReader::unreadChar (int c)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBInputStreamReader\fP\&.
.PP
Definition at line \fB1729\fP of file \fBtestlib\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for competitive-contest from the source code\&.
