.TH "TestlibFinalizeGuard" 3 "competitive-contest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestlibFinalizeGuard
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <testlib\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestlibFinalizeGuard\fP ()"
.br
.ti -1c
.RI "\fB~TestlibFinalizeGuard\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBquitCount\fP"
.br
.ti -1c
.RI "int \fBreadEofCount\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBalive\fP = true"
.br
.ti -1c
.RI "static bool \fBregistered\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB2770\fP of file \fBtestlib\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TestlibFinalizeGuard::TestlibFinalizeGuard ()\fR [inline]\fP"

.PP
Definition at line \fB2776\fP of file \fBtestlib\&.h\fP\&.
.SS "TestlibFinalizeGuard::~TestlibFinalizeGuard ()\fR [inline]\fP"

.PP
Definition at line \fB2780\fP of file \fBtestlib\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool TestlibFinalizeGuard::alive = true\fR [static]\fP"

.PP
Definition at line \fB2771\fP of file \fBtestlib\&.h\fP\&.
.SS "int TestlibFinalizeGuard::quitCount"

.PP
Definition at line \fB2774\fP of file \fBtestlib\&.h\fP\&.
.SS "int TestlibFinalizeGuard::readEofCount"

.PP
Definition at line \fB2774\fP of file \fBtestlib\&.h\fP\&.
.SS "bool TestlibFinalizeGuard::registered = false\fR [static]\fP"

.PP
Definition at line \fB2772\fP of file \fBtestlib\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for competitive-contest from the source code\&.
