.TH "src/validator.cpp" 3 "competitive-contest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/validator.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'testlib\&.h'\fP
.br
\fR#include <bits/stdc++\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBprime\fP (int x)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line \fB14\fP of file \fBvalidator\&.cpp\fP\&.
.SS "bool prime (int x)"

.PP
Definition at line \fB5\fP of file \fBvalidator\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for competitive-contest from the source code\&.
