.TH "ValidatorBoundsHit" 3 "competitive-contest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ValidatorBoundsHit
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <testlib\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValidatorBoundsHit\fP (bool \fBminHit\fP=false, bool \fBmaxHit\fP=false)"
.br
.ti -1c
.RI "\fBValidatorBoundsHit\fP \fBmerge\fP (const \fBValidatorBoundsHit\fP &validatorBoundsHit, bool ignoreMinBound, bool ignoreMaxBound)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBminHit\fP"
.br
.ti -1c
.RI "bool \fBmaxHit\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const double \fBEPS\fP = 1E\-12"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB2384\fP of file \fBtestlib\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ValidatorBoundsHit::ValidatorBoundsHit (bool minHit = \fRfalse\fP, bool maxHit = \fRfalse\fP)\fR [inline]\fP"

.PP
Definition at line \fB2389\fP of file \fBtestlib\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBValidatorBoundsHit\fP ValidatorBoundsHit::merge (const \fBValidatorBoundsHit\fP & validatorBoundsHit, bool ignoreMinBound, bool ignoreMaxBound)\fR [inline]\fP"

.PP
Definition at line \fB2392\fP of file \fBtestlib\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const double ValidatorBoundsHit::EPS = 1E\-12\fR [static]\fP"

.PP
Definition at line \fB2385\fP of file \fBtestlib\&.h\fP\&.
.SS "bool ValidatorBoundsHit::maxHit"

.PP
Definition at line \fB2387\fP of file \fBtestlib\&.h\fP\&.
.SS "bool ValidatorBoundsHit::minHit"

.PP
Definition at line \fB2386\fP of file \fBtestlib\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for competitive-contest from the source code\&.
